rule container:
    shell: "docker-compose up"

rule vulDatabase:
    input:
	"~/Documents/Rivka+Lotte/BioProject2/app/databaseData.txt"
    script:"~/Documents/Rivka+Lotte/BioProject2/app/vulDatabase.py {input}"

rule vindVariant:
    input:
	"~/Documents/Rivka+Lotte/BioProject2/app/inputFile.txt"
    script:"~/Documents/Rivka+Lotte/BioProject2/app/app.py {input}"
